# -*- coding: utf-8 -*-
"""devops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iJPCR7ps2kvlWCWM85SKjpFQxdOq2pEZ
"""

import requests
import json

# Authenticate to Azure DevOps
access_token = "your_access_token"
headers = {
    "Content-Type": "application/json",
    "Authorization": "Bearer " + access_token
}

# Define the fields for the work item
fields = {
    "System.Title": "Example Work Item",
    "System.Description": "This is an example work item"
}

# Create a new work item
url = "https://dev.azure.com/{organization}/{project}/_apis/wit/workitems/${work_item_type}?api-version=6.0"
response = requests.post(url, headers=headers, data=json.dumps(fields))

# Check the response
if response.status_code == 200:
    print("Work item created successfully")
else:
    print("Failed to create work item")
    print(response.content)